-- Add missing columns to drugs table
ALTER TABLE drugs 
ADD COLUMN dose varchar(100) NULL AFTER unit,
ADD COLUMN barcode varchar(255) NULL AFTER drug_code,
ADD COLUMN is_controlled_substance tinyint(1) NULL DEFAULT 0 AFTER barcode,
ADD COLUMN ndc_10 varchar(20) NULL AFTER is_controlled_substance,
ADD COLUMN ndc_11 varchar(20) NULL AFTER ndc_10,
ADD COLUMN quantity int(11) NULL DEFAULT 0 AFTER ndc_11,
ADD COLUMN quantity_unit varchar(20) NULL DEFAULT 'vial' AFTER quantity,
ADD COLUMN lot_number varchar(50) NULL AFTER quantity_unit,
ADD COLUMN expiration_date date NULL AFTER lot_number,
ADD COLUMN status enum('active','inactive','discontinued') NULL DEFAULT 'active' AFTER expiration_date,
ADD COLUMN removal_reason varchar(100) NULL AFTER status,
ADD COLUMN removal_notes text NULL AFTER removal_reason,
ADD COLUMN removed_by int(11) NULL AFTER removal_notes,
ADD COLUMN removed_date timestamp NULL AFTER removed_by;

-- Add indexes for the new columns
ALTER TABLE drugs 
ADD INDEX idx_barcode (barcode),
ADD INDEX idx_is_controlled_substance (is_controlled_substance),
ADD INDEX idx_ndc_10 (ndc_10),
ADD INDEX idx_ndc_11 (ndc_11),
ADD INDEX idx_lot_number (lot_number);

-- Create form_enhanced_infusion_injection table
CREATE TABLE IF NOT EXISTS form_enhanced_infusion_injection (
    id bigint(20) NOT NULL AUTO_INCREMENT,
    uuid binary(16) NULL,
    date datetime NULL,
    pid bigint(20) NULL DEFAULT 0,
    encounter bigint(20) NULL DEFAULT 0,
    user varchar(255) NULL,
    groupname varchar(255) NULL,
    authorized tinyint(4) NULL DEFAULT 0,
    activity tinyint(4) NULL DEFAULT 0,
    assessment text NULL,
    iv_access_type varchar(255) NULL,
    iv_access_location varchar(255) NULL,
    iv_access_blood_return varchar(3) NULL,
    iv_access_needle_gauge varchar(255) NULL,
    iv_access_attempts varchar(255) NULL,
    iv_access_date date NULL,
    iv_access_comments text NULL,
    order_medication varchar(255) NULL,
    order_dose varchar(255) NULL,
    order_strength varchar(255) NULL,
    order_lot_number varchar(255) NULL,
    order_ndc varchar(255) NULL,
    order_expiration_date date NULL,
    order_every_value varchar(255) NULL,
    order_every_unit varchar(255) NULL,
    order_servicing_provider varchar(255) NULL,
    order_npi varchar(255) NULL,
    order_end_date date NULL,
    order_note text NULL,
    administration_start datetime NULL,
    administration_end datetime NULL,
    administration_rate varchar(255) NULL,
    administration_rate_unit varchar(255) NULL,
    administration_route varchar(255) NULL,
    administration_site varchar(255) NULL,
    administration_comments text NULL,
    administration_duration varchar(10) NULL,
    wastage_quantity decimal(10,2) NULL,
    wastage_reason varchar(100) NULL,
    wastage_notes text NULL,
    administration_note text NULL,
    diagnoses text NULL,
    bp_systolic varchar(40) NULL,
    bp_diastolic varchar(40) NULL,
    pulse varchar(40) NULL,
    temperature_f varchar(40) NULL,
    oxygen_saturation varchar(40) NULL,
    respiratory_rate varchar(40) NULL,
    weight varchar(40) NULL,
    height varchar(40) NULL,
    inventory_drug_id int(11) NULL,
    inventory_lot_number varchar(50) NULL,
    inventory_quantity_used decimal(10,2) NULL,
    inventory_wastage_quantity decimal(10,2) NULL,
    inventory_wastage_reason varchar(100) NULL,
    inventory_reservation_id int(11) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uuid (uuid),
    KEY pid (pid),
    KEY encounter (encounter),
    KEY inventory_drug_id (inventory_drug_id),
    KEY inventory_lot_number (inventory_lot_number)
);

-- Create form_infusion_injection table
CREATE TABLE IF NOT EXISTS form_infusion_injection (
    id bigint(20) NOT NULL AUTO_INCREMENT,
    uuid binary(16) NULL,
    date datetime NULL,
    pid bigint(20) NULL DEFAULT 0,
    encounter bigint(20) NULL DEFAULT 0,
    user varchar(255) NULL,
    groupname varchar(255) NULL,
    authorized tinyint(4) NULL DEFAULT 0,
    activity tinyint(4) NULL DEFAULT 0,
    assessment text NULL,
    iv_access_type varchar(255) NULL,
    iv_access_location varchar(255) NULL,
    iv_access_blood_return varchar(3) NULL,
    iv_access_needle_gauge varchar(255) NULL,
    iv_access_attempts varchar(255) NULL,
    iv_access_comments text NULL,
    order_medication varchar(255) NULL,
    order_dose varchar(255) NULL,
    order_lot_number varchar(255) NULL,
    order_ndc varchar(255) NULL,
    order_expiration_date date NULL,
    order_every_value varchar(255) NULL,
    order_every_unit varchar(255) NULL,
    order_servicing_provider varchar(255) NULL DEFAULT 'Moussa El-hallak, M.D.',
    order_npi varchar(255) NULL DEFAULT '1831381524',
    order_note text NULL,
    administration_start datetime NULL,
    administration_end datetime NULL,
    administration_note text NULL,
    bp_systolic varchar(40) NULL,
    bp_diastolic varchar(40) NULL,
    pulse varchar(40) NULL,
    temperature_f varchar(40) NULL,
    oxygen_saturation varchar(40) NULL,
    inventory_drug_id int(11) NULL,
    inventory_lot_number varchar(50) NULL,
    inventory_quantity_used decimal(10,2) NULL,
    inventory_wastage_quantity decimal(10,2) NULL,
    inventory_wastage_reason varchar(100) NULL,
    inventory_reservation_id int(11) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uuid (uuid),
    KEY pid (pid),
    KEY encounter (encounter),
    KEY inventory_drug_id (inventory_drug_id),
    KEY inventory_lot_number (inventory_lot_number)
);

-- Create infusion_inventory_usage table
CREATE TABLE IF NOT EXISTS infusion_inventory_usage (
    id int(11) NOT NULL AUTO_INCREMENT,
    infusion_form_id int(11) NOT NULL,
    drug_id int(11) NOT NULL,
    lot_number varchar(50) NULL,
    quantity_ordered decimal(10,2) NOT NULL,
    quantity_used decimal(10,2) NOT NULL,
    quantity_wasted decimal(10,2) NULL DEFAULT 0.00,
    wastage_reason varchar(100) NULL,
    wastage_notes text NULL,
    created_by int(11) NOT NULL,
    created_date timestamp NULL DEFAULT current_timestamp(),
    PRIMARY KEY (id),
    KEY infusion_form_id (infusion_form_id),
    KEY drug_id (drug_id),
    KEY lot_number (lot_number),
    KEY created_date (created_date)
);

-- Create infusion_wastage_reasons table
CREATE TABLE IF NOT EXISTS infusion_wastage_reasons (
    id int(11) NOT NULL AUTO_INCREMENT,
    reason_code varchar(20) NOT NULL,
    reason_description varchar(255) NOT NULL,
    is_active tinyint(1) NULL DEFAULT 1,
    created_date timestamp NULL DEFAULT current_timestamp(),
    PRIMARY KEY (id),
    UNIQUE KEY reason_code (reason_code)
);

-- Insert default wastage reasons
INSERT INTO infusion_wastage_reasons (reason_code, reason_description, is_active) VALUES
('EXPIRED', 'Expired medication', 1),
('CONTAMINATED', 'Contaminated medication', 1),
('SPILLED', 'Spilled during administration', 1),
('PATIENT_REACTION', 'Patient had adverse reaction', 1),
('EQUIPMENT_FAILURE', 'Equipment failure during administration', 1),
('WRONG_DOSE', 'Wrong dose prepared', 1),
('PATIENT_REFUSED', 'Patient refused medication', 1),
('OTHER', 'Other reason', 1); 